<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net481</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		<Platforms>x86</Platforms>
		<AssemblyName>Content</AssemblyName>
		<RootNamespace>Content</RootNamespace>
		<StartupObject>Content</StartupObject>
		<FileVersion>4.0.30901.0</FileVersion>
                <ApplicationIcon>Package.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Content\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="lib\**" />
	  <EmbeddedResource Remove="lib\**" />
	  <None Remove="lib\**" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Content.cs" />
	  <Content Include="Package.ico" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\RolePlayingGameProcessors\RolePlayingGameProcessors.csproj" />
	</ItemGroup>

	<ItemGroup>
          <Reference Include="Content.Build.Tool">
	  	<HintPath>lib\Content.Build.Tool.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Microsoft.Build" />
	  <Reference Include="Microsoft.Build.Framework" />
	  <Reference Include="System.Configuration" />
	</ItemGroup>

</Project>
